### ISSUE TITLE
MDC Domain Type Inquiry

### ISSUE THREAD

**Issue by ChristopherDavenport** [ChristopherDavenport/log4cats#119]
It has been raised to my attention that `(String, String)*` is not a very desirable type to work with for MDC, and that perhaps a `Map[String, String]` would be better.

What was originally selected was done so in parity with the underlying SLF4J.

https://github.com/ChristopherDavenport/log4cats/blob/master/cats/slf4j-internal/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/LoggerMacros.scala#L166

Which applied each into the mapped diagnostic context. However I can see that generally you likely do not want more than 1 entry for a single key, and as a result. 

If we switch to map - What behavior do we want to see if that Map already contains a key from a higher level logger, should that be overridden in the lower logger if it is applied in the map?

Comments very appreciated.

**Comment by SystemFw** [comment]
More specific wins (so, lower level wins) seems reasonable.

> However I can see that generally you likely do not want more than 1 entry for a single key, and as a result.

Funnily enough we would like this, but it's fine anyway because currently no one supports it: use case is traceTokens, and nested/aggregated multiple tokens for the same thing would be nice. But in any case our log aggregator wouldn't support it, so meh

**Comment by ChristopherDavenport** [comment]
One of the ways I see it would be easier to support multiple responses
`Map[String, Chain[String]]` - Or list if expected pattern is always appending to head.

**Comment by SystemFw** [comment]
Yeah, but tbh that would make it harder for the vastly more common case when you have only one, and we would still be blocked by the log aggregator not supporting that, so personally I'd be happy with just `Map[String, String]`, which also makes transition easy for users that don't care about any of this, since they only need to add `Map(` around their existing code
