### ISSUE TITLE
Move Non-Stable projects into their own Projects

### ISSUE THREAD

**Issue by ChristopherDavenport** [ChristopherDavenport/log4cats#136]
- scalaz
- log4s
- scribe

These are all great backends that I want to keep available, however their existence precludes the ability to go to a 1.0 release because they are massively changing quickly and will increment the core quickly.

I want to propose a core project that has the data construction, and the default slf4j backend that I believe is mainly stable. Then with these other projects we can keep versions that can increment with their evolving backends.

**Comment by lorandszakacs** [comment]
Agree with this. 

From a build point of view, how would this look like?

Instead of having a root that aggregates all projects would we have 4 "root" projects? Something like:
```
lazy val `log4cats-stable` = project.in(file("."))
  .aggregate(
    //stable modules
  )

lazy val `log4cats-scalaz` = project.in(file(".")
  .aggregate(
    //scalaz-zio modules...
  )
//and so on?
```
And then when it comes to release time we'd do `sbt/log4cats-stable releaseMagic`? — honestly not sure how release is triggered from `travis` 😅

**Comment by ChristopherDavenport** [comment]
I think I would instead put them into their own projects, and version them seperately like I have done for epimetheus.

Makes the compatibility matrix a little tough, but then I just manage that so its clear on the subprojects.

**Comment by ChristopherDavenport** [comment]
This has been completed
