### ISSUE TITLE
MDC regression between 0.3.0 and 0.4.0-M1

### ISSUE THREAD

**Issue by lorandszakacs** [ChristopherDavenport/log4cats#187]
For a simple setup like this:
build.sbt
```
libraryDependencies += "io.chrisdavenport" %% "log4cats-slf4j" % "0.4.0-M1" withSources()
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.2.3" withSources()
```

Log4CatsMDC.scala:
```scala
package bug

import cats._
import cats.implicits._
import cats.effect._
import io.chrisdavenport.log4cats.slf4j._

object Log4CatsMDC extends IOApp {
  private val logger = Slf4jLogger.getLogger[IO]
  override def run(args: List[String]): IO[ExitCode] = {
    for {
      _ <- logger.info(Map("p1" -> "value"))("w/ MDC")
      _ <- logger.info("w/o MDC")
    } yield ExitCode.Success
  }
}
```

logback.xml:
```
<configuration>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>[%thread] %highlight(%-5level) %cyan(%logger) - %mdc — %msg %n
            </pattern>
        </encoder>
    </appender>

    <root level="DEBUG">
        <appender-ref ref="CONSOLE"/>
    </root>
</configuration>
```
With no other changes except log4cats version, we get:

✅ `0.3.0` 
```
[scala-execution-context-global-479] INFO  bug.Log4CatsMDC - p1=value — w/ MDC 
[scala-execution-context-global-479] INFO  bug.Log4CatsMDC -  — w/o MDC 
```

❌ `0.4.0-M1`
```
[ioapp-compute-0] INFO  bug.Log4CatsMDC -  — w/ MDC 
[ioapp-compute-0] INFO  bug.Log4CatsMDC -  — w/o MDC
```

As you can see, MDC key/value pairs no longer show up in logs 😢

**Comment by oleg-py** [comment]
Probably due to this:
https://github.com/ChristopherDavenport/log4cats/blob/9f17ba86ae222793fda5b2d99f2454a14d706cd8/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala#L29

`finally` section is executed earlier than effect represented by `logging`, resetting the context map before actual logging happens. It should at least use `bracket`/`guarantee`.

However, it would probably be better to do the opposite - pass `logging` as thunk of `() => Unit`. You can't quite know if action in `guarantee` call will execute immediately or on the same thread (it usually would, but it's an unspecified behavior that current effect types have, not something required by a law)
