### ISSUE TITLE
Could use `implicit F: Defer: Applicative` instead of `F: Sync` here?

### ISSUE THREAD

**Issue by DougC** [ChristopherDavenport/log4cats#266]
The use of `Sync` here propagates out to any code that wants to use the logger. If instead, it used `F: Defer: Applicative` and all the instances of `F.delay(x)` were changed to `F.defer(x.pure[F])` then this would relax the requirements and only reference type classes from cats-core instead of cats-effect.

This is quite a big change, however, as the typeclass constraints will propagate out through all the other layers of `log4cats`.

https://github.com/ChristopherDavenport/log4cats/blob/e84f1bd6e0990a1cb7b8006ba869ed068a354303/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala#L44

**Comment by ChristopherDavenport** [comment]
Is this appropriate though. We are definitively executing an external effect are we not. Defer is not intended to capture effects I do not believe.

**Comment by DougC** [comment]
Hmm. Why would you defer something that didn't have an effect? Making a cpu-intensive calculation lazy, maybe?

The trouble is that `Sync` brings a lot of baggage with it - `Bracket`, `Monad`, `MonadError`, etc (and it also extends `Defer`) that are irrelevant to the logger and mean the loggers can't be used with a monad that provides laziness without having pretty much a full cats-effect implementation. But also, I accept that this is largely a theoretical benefit.

I guess where I'm coming from with this is in trying to represent the least amount of power needed to describe what's needed.

**Comment by ChristopherDavenport** [comment]
I totally see where you are coming from, I believe the point of Defer is not side-effects but lazy calculations. As an Example, `Eval` has an instance, which is not intended for side-effects at all.

For example we can use Defer in Http4s so that we suspend the evaluation of the match statements in secondary Kleislis, so we only evaluate one kleisli at a time before moving onto the next set of routes. 

Sync is definitely a strong constraint but I believe it is the weakest constraint that expresses that arbitrary side-effects can be executed. I believe there is discussion of seperating this out in cats-effect 3, but I do not know of anything that only models suspension of arbitary effects presently without being so constrained via the hierarchy.

**Comment by DougC** [comment]
Okay, that's an interesting distinction. Would it make sense to say that in general an implementation of  Defer could expect to be evaluated with `.run` but that evaluating an implementation of Sync should require a call to `.unsafeRun*`, making it clear there are arbitrary side-effects?

**Comment by Daenyth** [comment]
I think the distinction is that `Defer` is an operational concern only - that you should be able to replace any instance of `defer` with `pure` without changing the return value semantics (only changing *when* a computation is executed)
