### ISSUE TITLE
MDC is not cleared on task cancellation

### ISSUE THREAD

**Issue by ikempf** [ChristopherDavenport/log4cats#274]
In the case where the logging task (with a context for MDC) gets cancelled, the MDC context is not cleared/restored to it's previous state.

Here is an [example code](https://github.com/ikempf/log4cats-mdc-clear/blob/master/src/main/scala/com/ikempf/Start.scala) that quickly produces the issue. A log setting the MDC context gets cancelled. Other log tasks then randomly display keys from the "leaked" MDC context. 

I've had a look at the [MDC related code](https://github.com/ChristopherDavenport/log4cats/blob/master/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala). I was about to suggest using a `Resource` or a `Bracket` to clear/restore the MDC to it's previous state but that's already the case.
I'm not sure why this is not working as expected 🤔, I'll have another look this weekend.

**Comment by kubukoz** [comment]
Could it be that in case of cancelation, bracket cleanup can run on a different thread than the `use`? I'm pretty sure that's what happens (canceling a bracket will first send a cancelation signal to the `use`, wait for it (in case of synchronous actions without an explicit cancel boundary it'll just proceed instead of waiting) and run the cleanup.

**Comment by kubukoz** [comment]
So, I assume that the context is actually restored to the previous state. Just not on the right thread (which I think is even worse than not doing it at all!).

```scala
  private[this] def contextLog[F[_]](
      isEnabled: F[Boolean],
      ctx: Map[String, String],
      logging: F[Unit]
  )(implicit F: Sync[F]): F[Unit] =
    isEnabled.ifM(
      F.delay { MDC.getCopyOfContextMap }
        .bracket { _ =>
          F.delay {
            for {
              (k, v) <- ctx
            } MDC.put(k, v)
          } >> logging
        } { backup =>
          F.delay {
            if (backup eq null) MDC.clear()
            else MDC.setContextMap(backup)
          }
        },
      F.unit
    )
```

We can't keep the bracket in the current form, because there's no way we can enforce restoring the MDC context on the thread that actually set it: we're no longer on that thread in the cleanup action, and something else might already be running there.

...but:

Since the only `logging: F[Unit]` action possible in this place is a synchronous logging call, I'd get rid of the bracket (`delay` can't be canceled anyway) and pass the logging action as a thunk or `SyncIO`, then `()` / `unsafeRunSync()` it, then wrap the logging in a try-catch that handles MDC.

**Comment by ChristopherDavenport** [comment]
I had that previously, we can restore. It was easier to read anyways. 😄

**Comment by ikempf** [comment]
The thread switching makes total sense, didn't event think about that 🤦‍♂. MDC is a pain to work around.
